apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: kafkas.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: kafka
        plural: kafkas
        singular: kafka
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  size:
                    default: small
                    description: |
                      Size of this kafka deployment. If small, it deploy kafka with a single replica; if large, deploy kafka with 3 replicas.
                    pattern: ^(small|large)$
                    type: string
                type: object
            type: object
        served: true
        storage: true
  destinationSelectors:
  - matchLabels:
      environment: dev
  workflows:
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
          namespace: default
        spec:
          containers:
          - image: hoangndst/kratix-marketplace/kafka-configure-pipeline:v0.1.0
            name: configure
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
          namespace: default
        spec:
          containers:
          - image: hoangndst/kratix-marketplace/kafka-configure-promise-pipeline:v0.1.0
            name: configure
status: {}
