apiVersion: example.promise.syntasso.io/v1
kind: app
metadata:
  name: app-as-a-service-demo
  namespace: default
spec:
  name: todo
  image: syntasso/sample-todo-app:v0.1.2
  dbDriver: postgres
  containsCreditCardData: false
